export const FONT_PRESETS = [
    {
        id: "inter",
        name: "Inter",
        fontName: "Inter",
        family: "Inter, system-ui, -apple-system, sans-serif",
        googleFont: "Inter:wght@300;400;500;600;700;800",
    },
    {
        id: "plus-jakarta-sans",
        name: "Plus Jakarta Sans",
        fontName: "Plus Jakarta Sans",
        family: '"Plus Jakarta Sans", system-ui, -apple-system, sans-serif',
        googleFont: "Plus+Jakarta+Sans:wght@300;400;500;600;700;800",
    },
    {
        id: "outfit",
        name: "Outfit",
        fontName: "Outfit",
        family: "Outfit, system-ui, -apple-system, sans-serif",
        googleFont: "Outfit:wght@300;400;500;600;700;800",
    },
    {
        id: "poppins",
        name: "Poppins",
        fontName: "Poppins",
        family: "Poppins, system-ui, -apple-system, sans-serif",
        googleFont: "Poppins:wght@300;400;500;600;700;800",
    },
    {
        id: "roboto",
        name: "Roboto",
        fontName: "Roboto",
        family: "Roboto, system-ui, -apple-system, sans-serif",
        googleFont: "Roboto:wght@300;400;500;700",
    },
    {
        id: "space-grotesk",
        name: "Space Grotesk",
        fontName: "Space Grotesk",
        family: '"Space Grotesk", system-ui, -apple-system, sans-serif',
        googleFont: "Space+Grotesk:wght@300;400;500;600;700",
    },
    {
        id: "montserrat",
        name: "Montserrat",
        fontName: "Montserrat",
        family: "Montserrat, system-ui, -apple-system, sans-serif",
        googleFont: "Montserrat:wght@300;400;500;600;700;800",
    },
    {
        id: "dm-sans",
        name: "DM Sans",
        fontName: "DM Sans",
        family: '"DM Sans", system-ui, -apple-system, sans-serif',
        googleFont: "DM+Sans:wght@300;400;500;600;700",
    },
    {
        id: "manrope",
        name: "Manrope",
        fontName: "Manrope",
        family: "Manrope, system-ui, -apple-system, sans-serif",
        googleFont: "Manrope:wght@300;400;500;600;700;800",
    },
    {
        id: "raleway",
        name: "Raleway",
        fontName: "Raleway",
        family: "Raleway, system-ui, -apple-system, sans-serif",
        googleFont: "Raleway:wght@300;400;500;600;700;800",
    },
    {
        id: "rubik",
        name: "Rubik",
        fontName: "Rubik",
        family: "Rubik, system-ui, -apple-system, sans-serif",
        googleFont: "Rubik:wght@300;400;500;600;700",
    },
    {
        id: "urbanist",
        name: "Urbanist",
        fontName: "Urbanist",
        family: "Urbanist, system-ui, -apple-system, sans-serif",
        googleFont: "Urbanist:wght@300;400;500;600;700;800",
    },
    {
        id: "sora",
        name: "Sora",
        fontName: "Sora",
        family: "Sora, system-ui, -apple-system, sans-serif",
        googleFont: "Sora:wght@300;400;500;600;700;800",
    },
    {
        id: "system",
        name: "System Default",
        fontName: "System",
        family: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
        googleFont: null,
    },
];

export const DEFAULT_FONT_PRESET = FONT_PRESETS[1]; // Plus Jakarta Sans (current Firestore setting)
